DATA_URLS = {
    "apple": "https://drive.google.com/file/d/1lmQln6UbZL8Amn-K_rpjGMR-O6cov3zF/view?usp=drive_link",
    "plant": "https://drive.google.com/file/d/1SKl6Ls5szGwxzfrkk_EQZfDtkzNwuJSZ/view?usp=drive_link",
    "fruits": "https://drive.google.com/file/d/1WBO1c_mQ3jPL1oXbSaPpipCBOjkXSOJA/view?usp=drive_link",
    "empty": "https://drive.google.com/file/d/15w_mHORvzjiAH5VAhRA6NKnJ6nO_YQr2/view?usp=drive_link",
    "lego": "https://drive.google.com/file/d/19f9MHSxeSaL188R8PLjv74R9fwSeGJp0/view?usp=drive_link",
    "tapes": "https://drive.google.com/file/d/1ZgdzI4aOz17RfmwyeCIH-ysZDe_mpW3S/view?usp=drive_link",
    "wooden": "https://drive.google.com/file/d/1kPp_KvWmkaFa2c4hKIfxEXfhMfJGYez7/view?usp=drive_link",
    "cheetah": "https://drive.google.com/file/d/1ZpvcFoGUuphgChAPIykqLvNOU4QbVyA9/view?usp=drive_link",
    "shark": "https://drive.google.com/file/d/1o-WPRyvgu4XBAGyjogTaAXW89Z2e_Ru5/view?usp=drive_link",
    "lunch": "https://drive.google.com/file/d/1mIa9Oym8P94MfMjri6Fl3H3tY0hNTXMw/view?usp=drive_link",
    "reflective": "https://drive.google.com/file/d/1wakjIOJ_U3P3m6qxD7m2e4IxWvLSV4ne/view?usp=drive_link",
    "flipflop": "https://drive.google.com/file/d/15xZaVUr1pKcEIlB49fV6iGI9zXVpqiZv/view?usp=drive_link",
    "robotoy": "https://drive.google.com/file/d/1jK5s20Oca7uowHUfNJX1Qa8nQGrTnStH/view?usp=drive_link",
    "cube": "https://drive.google.com/file/d/1FvtxraK1L_vvBg32syXC-znSA6Up6imP/view?usp=drive_link",
    "trucks": "https://drive.google.com/file/d/1uNoFKvgHAYEg21zsrd8sjmmiHhA-B8mx/view?usp=drive_link",
    "garden": "https://drive.google.com/file/d/12Ox_SYtLgUBpFE2acMQFoqe0ijggU8gr/view?usp=drive_link",
    "stegosaurus": "https://drive.google.com/file/d/1kTWXbtNlR1yfLPooqkS6WxM47XvEwS8E/view?usp=drive_link",
    "dinosaurs": "https://drive.google.com/file/d/1pv5-HYO4bsveMgrz_CYdaKsT-nJE3zcD/view?usp=drive_link",
    "helicopters": "https://drive.google.com/file/d/1YH90CqP-YYlK6CzrYU_pA7KoNmmVEuLF/view?usp=drive_link",
    "savannah": "https://drive.google.com/file/d/1YOzhXavlUW-JmHHmatFjFIsfTyYBpyqE/view?usp=drive_link",
    "kittens": "https://drive.google.com/file/d/1JV1_D8JHPpLJFF68NtFt4U5tZL7nPQlK/view?usp=drive_link",
}

DATA_KEYS = list(DATA_URLS.keys())
